server.port=8070
spring.application.name=VOD cinemas
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/vod
spring.datasource.username=root
spring.datasource.password=mysql

ms.movie.service.url=http://localhost:8090/webapi
